### ISSUE TITLE
About Contact form 

### ISSUE THREAD

**Issue by AvinashAnand02** [SRIKANTH284/myinfo#1]
hi 
change the code and put your service id and template id so that you are able to recive the mail regarding that 

`emailjs.init("3EvNyKZKcMLcyTKQN");
    console.log("form submitted");
    emailjs.sendForm('service_xol5sv7', 'template_133u14v', '#contact-form')`

**Comment by SRIKANTH284** [comment]
Hi Avinash
can you please help me on this i'm facing some issues
your help would be appreciated

**Comment by AvinashAnand02** [comment]
Go to emailJS create account there and create a new template and remove my id through yours
